# Generated by Django 3.2 on 2021-04-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='primeiro nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='ultimo nome')),
                ('phone', models.CharField(blank=True, default='', max_length=16, verbose_name='telefone')),
                ('age', models.CharField(blank=True, default='', max_length=2, verbose_name='idade')),
                ('city', models.CharField(max_length=100, verbose_name='cidade')),
                ('email', models.EmailField(max_length=254)),
                ('obs', models.CharField(max_length=500, verbose_name='observação')),
                ('file', models.FileField(blank='true', default='', upload_to='media', verbose_name='Autorização dos resṕnsáveis')),
                ('food', models.CharField(blank=True, default='', max_length=100, verbose_name='Restrição Alimentar')),
                ('sleep', models.CharField(max_length=100, verbose_name='Alocação')),
            ],
        ),
    ]
