# Generated by Django 2.2.5 on 2019-09-04 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='employee',
        ),
    ]
