# Generated by Django 2.2.5 on 2019-09-04 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20190904_0010'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table=None,
        ),
    ]
