# Generated by Django 2.2.5 on 2019-09-04 00:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20190904_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
