# Generated by Django 2.2.5 on 2019-09-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_auto_20190904_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='file',
            field=models.FileField(upload_to='media'),
        ),
    ]
