# Generated by Django 2.2.5 on 2019-09-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_auto_20190904_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='food',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Restrição Alimentar'),
        ),
    ]
