# Generated by Django 2.2.5 on 2019-09-04 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_register_sleeping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='sleeping',
        ),
    ]
