# Generated by Django 2.2.5 on 2019-09-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_register_sleep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='file',
            field=models.FileField(blank='true', default='', upload_to='media', verbose_name='Autorização dos resṕnsáveis'),
        ),
    ]
