# Generated by Django 2.2.5 on 2019-09-05 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0011_auto_20190904_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='file',
        ),
    ]
