# Generated by Django 3.0.2 on 2020-01-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0013_register_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='church',
            field=models.CharField(max_length=100, verbose_name='igreja'),
        ),
        migrations.AlterField(
            model_name='register',
            name='city',
            field=models.CharField(max_length=100, verbose_name='cidade'),
        ),
    ]
